services:
  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - .backend/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  postgres-data:

networks:
  app-networks:
    driver: bridge
