services:
  postgres:
    build:
      context: "./db" 
    container_name: database
    restart: on-failure
    env_file:
      - .env
    ports:
        - "5432:5432"
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
